pipeline {
    agent any
    environment {
        MY_ENV = 'Bruno Nelli'
    }
    stages {
        stage('Creating directory, file and listing files') {
            steps {
                bat label: 'create_dir', script: 'mkdir test_directory'
                dir('test_directory') {
                    writeFile file: 'text_file.txt', text: ''
                    bat label: 'list_files', script: 'ls'
                }
            }
        }
        stage('Replacing Environment variable in text file') {
            steps {
                dir('test_directory') {
                    writeFile file:'text_file.txt', text:"${MY_ENV}"
                }
            }
        }
    }
    post {
        always{
            dir ('test_directory') {
                deleteDir()
            }
        }
    }
}
